services:
  movementservice:
    image: movementservice
    build:
      context: .
      dockerfile: MovementService/Dockerfile

  mapservice:
    image: mapservice
    build:
      context: .
      dockerfile: MapService/Dockerfile

  centralservice:
    image: centralservice
    build:
      context: .
      dockerfile: CentralService/Dockerfile

  dynamicmapservice:
    image: dynamicmapservice
    build:
      context: .
      dockerfile: DynamicMapService/Dockerfile
      
  goalQueue:
    container_name: goalQueue
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - goalQueue:/var/lib/goalQueue
        
volumes:
  goalQueue:
